import assert from 'node:assert/strict'
import test from 'node:test'
import { createRenderer, nextTick } from 'vue'
import { FlowUpload, createFlowUploadI18n } from '../dist/index.js'

/** 在真实 Vue 生命周期内运行上传组件状态，避免查询回归测试依赖浏览器 DOM。 Runs uploader state inside real Vue lifecycles without requiring browser DOM for query regression tests. */
function mountUpload(props) {
  // 仅渲染空节点；测试直接调用组件生成的删除弹窗事件。
  // Render only an empty node; tests invoke the removal dialog event generated by the component.
  const renderer = createRenderer({
    createComment: () => ({}),
    insert() {},
    remove() {},
    parentNode: () => null,
    nextSibling: () => null,
  })
  // 保存公开 API 和真实渲染函数，用于触发删除确认。
  // Capture the public API and actual render function to trigger removal confirmation.
  let api
  // 组件渲染函数提供弹窗当前的 busy 状态与确认回调。
  // The component render function provides the dialog's current busy state and confirmation callback.
  let renderUpload
  // 在 Vue 渲染上下文内捕获虚拟节点，以支持插槽与响应式更新。
  // Capture virtual nodes inside Vue's rendering context to support slots and reactive updates.
  let renderedUpload
  // 捕获组件事件，以验证卸载及文件数量限制不会修改宿主模型。
  // Capture component events to verify unmount and capacity limits do not alter the host model incorrectly.
  const events = []
  // 宿主仅用于提供组件实例与生命周期所有权。
  // The host only provides a component instance and lifecycle ownership.
  const app = renderer.createApp({
    setup() {
      renderUpload = FlowUpload.setup(
        { defaultFileList: [], modelValue: [], maxCount: Infinity, autoUpload: true, ...props },
        {
          emit: (name, ...payload) => events.push({ name, payload }),
          expose: (value) => {
            api = value
          },
        },
      )
      return () => {
        renderedUpload = renderUpload({ $slots: {} }, [])
        return null
      }
    },
  })
  app.use(createFlowUploadI18n())
  app.mount({})
  return {
    api,
    events,
    unmount: () => app.unmount(),
    selectFiles: (files) =>
      renderedUpload.children
        .find((child) => child.type?.__name === 'UploadTrigger')
        .props.onFiles(files),
    getDialog: () =>
      renderedUpload.children.find((child) => child.type?.__name === 'UploadRemoveDialog'),
  }
}

/**
 * 渲染删除弹窗的说明文本，直接断言单文件与批量删除的插值分支。
 * Renders deletion-dialog copy so single-file and batch-removal interpolation branches can be asserted directly.
 */
function renderRemovalMessage(dialog, files) {
  // 使用可识别的模板，确保批量分支不会意外带入任一文件名。
  // Uses recognizable templates to ensure the batch branch cannot accidentally include a filename.
  const renderDialog = dialog.type.setup(
    {
      files,
      busy: false,
      error: '',
      title: 'Removal confirmation',
      singleFileMessage: 'single:{name}',
      multipleFilesMessage: 'multiple:{count}',
      cancelText: 'Cancel',
      confirmText: 'Remove',
      processingText: 'Removing',
    },
    { emit() {} },
  )
  // 组件渲染结果先是 UploadModal；通过默认插槽取得确认内容，避免测试依赖 Teleport 的内部 VNode 层级。
  // The component first renders UploadModal; obtain the confirmation content through its default slot to avoid coupling to Teleport's internal VNode shape.
  const modal = renderDialog({}, [])
  // 默认插槽只包含确认 section，其内容区域的第二段即按数量分支后的说明文本。
  // The default slot contains only the confirmation section, whose content area's second paragraph is the count-dependent copy.
  return modal.children.default()[0].children[1].children[1].children
}

test('removal confirmation shows one filename but only the batch count', async () => {
  // 先打开真实弹窗以获取已编译的内部确认组件。
  // Opens the real dialog first to obtain the compiled internal confirmation component.
  const upload = mountUpload({
    belongId: 'test',
    belongType: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'one', fileId: 'one', name: 'invoice.pdf', size: 1, status: 'success' }],
    transport: { deleteFile: async () => {} },
  })
  try {
    await upload.api.remove('one')
    // 单个文件说明必须包含其名称。
    // Single-file copy must include that file's name.
    const singleMessage = renderRemovalMessage(upload.getDialog(), [
      { uid: 'one', name: 'invoice.pdf', size: 1, status: 'success' },
    ])
    // 批量说明只包含数量，不应展开任何文件名。
    // Batch copy contains only the count and must not expand any filename.
    const multipleMessage = renderRemovalMessage(upload.getDialog(), [
      { uid: 'one', name: 'invoice.pdf', size: 1, status: 'success' },
      { uid: 'two', name: 'contract.pdf', size: 1, status: 'success' },
    ])
    assert.equal(singleMessage, 'single:invoice.pdf')
    assert.equal(multipleMessage, 'multiple:2')
  } finally {
    upload.unmount()
  }
})

test('confirmed removal waits for a fresh server query before completing', async () => {
  // 记录删除与查询顺序，并控制后台回读何时完成。
  // Record deletion/query order and control when the server reload completes.
  const calls = []
  // 查询完成器模拟慢速后端。
  // The query resolver simulates a slow backend.
  let finishQuery
  // 标记删除确认是否已经结束。
  // Track whether deletion confirmation has finished.
  let isFinished = false
  // 已持久化文件必须经过真实删除确认流程。
  // A persisted file must pass through the real removal confirmation flow.
  const upload = mountUpload({
    belongId: 'test',
    belongType: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'old', fileId: 'old', name: 'old.txt', size: 1, status: 'success' }],
    transport: {
      deleteFile: async () => {
        calls.push('delete')
      },
    },
    queryTransport: {
      queryFiles: () => {
        calls.push('query')
        return new Promise((resolve) => {
          finishQuery = resolve
        })
      },
    },
  })
  try {
    await upload.api.remove('old')
    // 确认回调的 Promise 必须覆盖后台查询，而不仅是 DELETE。
    // The confirmation promise must cover the server query, not just DELETE.
    const removal = upload
      .getDialog()
      .props.onConfirm()
      .then(() => {
        isFinished = true
      })
    for (let attempt = 0; attempt < 20 && !finishQuery; attempt++) await nextTick()
    // 排空确认回调的微任务，确保未等待查询的旧实现会提前完成并被检测到。
    // Drain confirmation microtasks so the old non-awaited query would finish early and be detected.
    await nextTick()
    await nextTick()
    assert.deepEqual(calls, ['delete', 'query'])
    assert.equal(isFinished, false)
    assert.equal(upload.getDialog().props.busy, true)
    finishQuery({ files: [], pagination: { enabled: false } })
    await removal
    assert.equal(upload.getDialog().props.busy, false)
  } finally {
    upload.unmount()
  }
})

test('failed server deletion keeps the dialog open and does not reload the list', async () => {
  // 删除失败时不得发出查询或假装删除完成。
  // Failed deletion must neither issue a query nor pretend removal completed.
  let queryCount = 0
  // 失败适配器模拟后端拒绝删除。
  // The failing adapter simulates a backend rejecting deletion.
  const upload = mountUpload({
    belongId: 'test',
    belongType: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'old', fileId: 'old', name: 'old.txt', size: 1, status: 'success' }],
    transport: {
      deleteFile: async () => {
        throw new Error('DELETE_FAILED')
      },
    },
    queryTransport: {
      queryFiles: async () => {
        queryCount++
        return { files: [], pagination: { enabled: false } }
      },
    },
  })
  try {
    await upload.api.remove('old')
    await upload.getDialog().props.onConfirm()
    await nextTick()
    assert.equal(queryCount, 0)
    assert.equal(upload.getDialog().props.files.length, 1)
    assert.ok(upload.getDialog().props.error)
    assert.equal(upload.getDialog().props.busy, false)
  } finally {
    upload.unmount()
  }
})

test('unmount releases work without clearing the host file model', () => {
  // 受控列表由宿主持有，卸载组件不得发出空列表更新。
  // The host owns the controlled list, so unmount must not emit an empty replacement.
  const upload = mountUpload({
    belongId: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'saved', name: 'saved.txt', status: 'success' }],
  })
  upload.unmount()
  assert.equal(
    upload.events.some((event) => event.name === 'update:modelValue'),
    false,
  )
})

test('overlapping selections reserve max-count slots during asynchronous validation', async () => {
  // 第一批的两个文件在异步拦截期间仍占满容量。
  // Both files in the first batch reserve capacity while its guard is pending.
  let releaseFirst
  const upload = mountUpload({
    belongId: 'test',
    permissions: {},
    queryOnMount: false,
    autoUpload: false,
    maxCount: 2,
    beforeUpload: (file) =>
      file.name === 'first.txt'
        ? new Promise((resolve) => {
            releaseFirst = resolve
          })
        : true,
  })
  try {
    upload.selectFiles([new File(['a'], 'first.txt'), new File(['b'], 'second.txt')])
    upload.selectFiles([new File(['c'], 'third.txt')])
    assert.deepEqual(
      upload.events
        .filter((event) => event.name === 'exceed')
        .map((event) => event.payload[0][0].name),
      ['third.txt'],
    )
    releaseFirst(true)
    await nextTick()
    await nextTick()
    const latestFiles = upload.events.filter((event) => event.name === 'update:modelValue').at(-1)
      .payload[0]
    assert.deepEqual(
      latestFiles.map((file) => file.name),
      ['first.txt', 'second.txt'],
    )
  } finally {
    upload.unmount()
  }
})

test('clearing during validation prevents the remaining selected files from reappearing', async () => {
  // 清空后旧选择批次的异步校验不能继续插入下一文件。
  // A pending validation batch cannot insert its next file after an explicit clear.
  let releaseValidation
  const upload = mountUpload({
    belongId: 'test',
    permissions: {},
    queryOnMount: false,
    autoUpload: false,
    beforeUpload: () =>
      new Promise((resolve) => {
        releaseValidation = resolve
      }),
  })
  try {
    upload.selectFiles([new File(['a'], 'first.txt'), new File(['b'], 'second.txt')])
    upload.api.clear()
    releaseValidation(true)
    await nextTick()
    await nextTick()
    const updates = upload.events.filter((event) => event.name === 'update:modelValue')
    assert.deepEqual(updates.at(-1).payload[0], [])
  } finally {
    upload.unmount()
  }
})

test('a resumed upload ignores a late create-file result from its paused run', async () => {
  // 第一次预创建延迟返回，模拟暂停后旧请求晚于新请求完成。
  // Delay the first create response so it finishes after a resumed run.
  let finishOldCreate
  let createCount = 0
  let uploadCount = 0
  const upload = mountUpload({
    belongId: 'test',
    permissions: {},
    queryOnMount: false,
    transport: {
      createFile: () => {
        createCount += 1
        return createCount === 1
          ? new Promise((resolve) => {
              finishOldCreate = resolve
            })
          : Promise.resolve({ fileId: 'new' })
      },
      uploadFile: async () => {
        uploadCount += 1
        return { fileId: 'new', status: 'success' }
      },
    },
  })
  try {
    await upload.api.handleStart(new File(['a'], 'first.txt'))
    for (let attempt = 0; attempt < 20 && !finishOldCreate; attempt++) await nextTick()
    const uid = upload.events.find((event) => event.name === 'update:modelValue').payload[0][0].uid
    upload.api.pause(uid)
    const resumed = upload.api.resume(uid)
    finishOldCreate({ fileId: 'old' })
    await resumed
    assert.equal(createCount, 2)
    assert.equal(uploadCount, 1)
    const latestFiles = upload.events.filter((event) => event.name === 'update:modelValue').at(-1)
      .payload[0]
    assert.equal(latestFiles[0].fileId, 'new')
  } finally {
    upload.unmount()
  }
})

test('canceling an archive ignores a successful poll response already in flight', async () => {
  // 浏览器锚点只记录下载动作，不触碰真实 DOM。
  // The browser anchor records download actions without requiring a real DOM.
  const previousWindow = globalThis.window
  let downloadCount = 0
  globalThis.window = {
    setTimeout: globalThis.setTimeout,
    clearTimeout: globalThis.clearTimeout,
    document: {
      createElement: () => ({ style: {}, click: () => downloadCount++, remove() {} }),
      body: { append() {} },
    },
  }
  // 轮询已发出但尚未返回时取消任务。
  // Cancel the task while its poll is outstanding.
  let finishPoll
  const upload = mountUpload({
    belongId: 'test',
    permissions: {},
    queryOnMount: false,
    archivePollingInterval: 0,
    archivePollingTimeout: 1000,
    downloadTransport: {
      downloadFile: async () => ({}),
      createArchive: async () => ({ taskId: 'archive-1', status: 'pending' }),
      getArchiveTask: () =>
        new Promise((resolve) => {
          finishPoll = resolve
        }),
    },
  })
  try {
    const downloading = upload.api.downloadAll()
    for (let attempt = 0; attempt < 20 && !finishPoll; attempt++)
      await new Promise((resolve) => globalThis.setTimeout(resolve, 1))
    assert.equal(typeof finishPoll, 'function')
    await upload.api.cancelArchive('archive-1')
    finishPoll({
      taskId: 'archive-1',
      status: 'success',
      downloadUrl: 'https://example.test/archive.zip',
    })
    await downloading
    assert.equal(downloadCount, 0)
    assert.equal(
      upload.events.some((event) => event.name === 'archive-success'),
      false,
    )
  } finally {
    upload.unmount()
    globalThis.window = previousWindow
  }
})
