import assert from 'node:assert/strict'
import test from 'node:test'
import { createRenderer, nextTick } from 'vue'
import { FlowUpload, createFlowUploadI18n } from '../dist/index.js'

/** 在真实 Vue 生命周期内运行上传组件状态，避免查询回归测试依赖浏览器 DOM。 Runs uploader state inside real Vue lifecycles without requiring browser DOM for query regression tests. */
function mountUpload(props) {
  // 仅渲染空节点；测试直接调用组件生成的删除弹窗事件。
  // Render only an empty node; tests invoke the removal dialog event generated by the component.
  const renderer = createRenderer({
    createComment: () => ({}),
    insert() {},
    remove() {},
    parentNode: () => null,
    nextSibling: () => null,
  })
  // 保存公开 API 和真实渲染函数，用于触发删除确认。
  // Capture the public API and actual render function to trigger removal confirmation.
  let api
  // 组件渲染函数提供弹窗当前的 busy 状态与确认回调。
  // The component render function provides the dialog's current busy state and confirmation callback.
  let renderUpload
  // 在 Vue 渲染上下文内捕获虚拟节点，以支持插槽与响应式更新。
  // Capture virtual nodes inside Vue's rendering context to support slots and reactive updates.
  let renderedUpload
  // 宿主仅用于提供组件实例与生命周期所有权。
  // The host only provides a component instance and lifecycle ownership.
  const app = renderer.createApp({
    setup() {
      renderUpload = FlowUpload.setup(props, {
        emit() {},
        expose: (value) => {
          api = value
        },
      })
      return () => {
        renderedUpload = renderUpload({ $slots: {} }, [])
        return null
      }
    },
  })
  app.use(createFlowUploadI18n())
  app.mount({})
  return {
    api,
    unmount: () => app.unmount(),
    getDialog: () =>
      renderedUpload.children.find((child) => child.type?.__name === 'UploadRemoveDialog'),
  }
}

/**
 * 渲染删除弹窗的说明文本，直接断言单文件与批量删除的插值分支。
 * Renders deletion-dialog copy so single-file and batch-removal interpolation branches can be asserted directly.
 */
function renderRemovalMessage(dialog, files) {
  // 使用可识别的模板，确保批量分支不会意外带入任一文件名。
  // Uses recognizable templates to ensure the batch branch cannot accidentally include a filename.
  const renderDialog = dialog.type.setup(
    {
      files,
      busy: false,
      error: '',
      title: 'Removal confirmation',
      singleFileMessage: 'single:{name}',
      multipleFilesMessage: 'multiple:{count}',
      cancelText: 'Cancel',
      confirmText: 'Remove',
      processingText: 'Removing',
    },
    { emit() {} },
  )
  // 组件渲染结果先是 UploadModal；通过默认插槽取得确认内容，避免测试依赖 Teleport 的内部 VNode 层级。
  // The component first renders UploadModal; obtain the confirmation content through its default slot to avoid coupling to Teleport's internal VNode shape.
  const modal = renderDialog({}, [])
  // 默认插槽只包含确认 section，其内容区域的第二段即按数量分支后的说明文本。
  // The default slot contains only the confirmation section, whose content area's second paragraph is the count-dependent copy.
  return modal.children.default()[0].children[1].children[1].children
}

test('removal confirmation shows one filename but only the batch count', async () => {
  // 先打开真实弹窗以获取已编译的内部确认组件。
  // Opens the real dialog first to obtain the compiled internal confirmation component.
  const upload = mountUpload({
    belongId: 'test',
    belongType: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'one', fileId: 'one', name: 'invoice.pdf', size: 1, status: 'success' }],
    transport: { deleteFile: async () => {} },
  })
  try {
    await upload.api.remove('one')
    // 单个文件说明必须包含其名称。
    // Single-file copy must include that file's name.
    const singleMessage = renderRemovalMessage(upload.getDialog(), [
      { uid: 'one', name: 'invoice.pdf', size: 1, status: 'success' },
    ])
    // 批量说明只包含数量，不应展开任何文件名。
    // Batch copy contains only the count and must not expand any filename.
    const multipleMessage = renderRemovalMessage(upload.getDialog(), [
      { uid: 'one', name: 'invoice.pdf', size: 1, status: 'success' },
      { uid: 'two', name: 'contract.pdf', size: 1, status: 'success' },
    ])
    assert.equal(singleMessage, 'single:invoice.pdf')
    assert.equal(multipleMessage, 'multiple:2')
  } finally {
    upload.unmount()
  }
})

test('confirmed removal waits for a fresh server query before completing', async () => {
  // 记录删除与查询顺序，并控制后台回读何时完成。
  // Record deletion/query order and control when the server reload completes.
  const calls = []
  // 查询完成器模拟慢速后端。
  // The query resolver simulates a slow backend.
  let finishQuery
  // 标记删除确认是否已经结束。
  // Track whether deletion confirmation has finished.
  let isFinished = false
  // 已持久化文件必须经过真实删除确认流程。
  // A persisted file must pass through the real removal confirmation flow.
  const upload = mountUpload({
    belongId: 'test',
    belongType: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'old', fileId: 'old', name: 'old.txt', size: 1, status: 'success' }],
    transport: {
      deleteFile: async () => {
        calls.push('delete')
      },
    },
    queryTransport: {
      queryFiles: () => {
        calls.push('query')
        return new Promise((resolve) => {
          finishQuery = resolve
        })
      },
    },
  })
  try {
    await upload.api.remove('old')
    // 确认回调的 Promise 必须覆盖后台查询，而不仅是 DELETE。
    // The confirmation promise must cover the server query, not just DELETE.
    const removal = upload
      .getDialog()
      .props.onConfirm()
      .then(() => {
        isFinished = true
      })
    for (let attempt = 0; attempt < 20 && !finishQuery; attempt++) await nextTick()
    // 排空确认回调的微任务，确保未等待查询的旧实现会提前完成并被检测到。
    // Drain confirmation microtasks so the old non-awaited query would finish early and be detected.
    await nextTick()
    await nextTick()
    assert.deepEqual(calls, ['delete', 'query'])
    assert.equal(isFinished, false)
    assert.equal(upload.getDialog().props.busy, true)
    finishQuery({ files: [], pagination: { enabled: false } })
    await removal
    assert.equal(upload.getDialog().props.busy, false)
  } finally {
    upload.unmount()
  }
})

test('failed server deletion keeps the dialog open and does not reload the list', async () => {
  // 删除失败时不得发出查询或假装删除完成。
  // Failed deletion must neither issue a query nor pretend removal completed.
  let queryCount = 0
  // 失败适配器模拟后端拒绝删除。
  // The failing adapter simulates a backend rejecting deletion.
  const upload = mountUpload({
    belongId: 'test',
    belongType: 'test',
    permissions: {},
    queryOnMount: false,
    modelValue: [{ uid: 'old', fileId: 'old', name: 'old.txt', size: 1, status: 'success' }],
    transport: {
      deleteFile: async () => {
        throw new Error('DELETE_FAILED')
      },
    },
    queryTransport: {
      queryFiles: async () => {
        queryCount++
        return { files: [], pagination: { enabled: false } }
      },
    },
  })
  try {
    await upload.api.remove('old')
    await upload.getDialog().props.onConfirm()
    await nextTick()
    assert.equal(queryCount, 0)
    assert.equal(upload.getDialog().props.files.length, 1)
    assert.ok(upload.getDialog().props.error)
    assert.equal(upload.getDialog().props.busy, false)
  } finally {
    upload.unmount()
  }
})
