export interface UploadMessages {
  selectFile: string
  chooseFile: string
  uploadLimits: string
  allFileTypes: string
  unlimited: string
  dragHint: string
  dragUpload: string
  dropToUpload: string
  startUpload: string
  pause: string
  resume: string
  retry: string
  remove: string
  preview: string
  download: string
  downloadSelected: string
  downloadAll: string
  closePreview: string
  uploadFailed: string
  waiting: string
  validating: string
  hashing: string
  checking: string
  uploading: string
  paused: string
  completed: string
  canceled: string
  rejected: string
  fileTooLarge: string
  fileTypeNotAllowed: string
  beforeUploadRejected: string
  pendingFiles: string
  selectAll: string
  fileActions: string
  selectedFiles: string
  removeSelected: string
  fileCount: string
  removeConfirmTitle: string
  removeConfirmMessage: string
  removeConfirmProcessing: string
  cancel: string
  removeCleanupFailed: string
  uploadingToast: string
  noUploadFilesToast: string
  noDownloadFilesToast: string
  noRemoveFilesToast: string
  uploadFile: string
  avatar: string
  avatarInvalidType: string
  avatarTooLarge: string
  avatarSelectFirst: string
  avatarNotReady: string
  avatarUploadFailed: string
  avatarUploadFailedWithStatus: string
  avatarTransportNotConfigured: string
  avatarDeleteFailed: string
  avatarPreview: string
  avatarUpdate: string
  avatarDragHint: string
  avatarDropToUpload: string
  avatarChoose: string
  avatarUpload: string
  paginationTotal: string
  paginationItemsPerPage: string
  paginationPrevious: string
  paginationNext: string
  paginationPageNumber: string
  paginationGoTo: string
  paginationLabel: string
}
export interface ThemeAdapter {
  name: string
  className?: string
  variables?: Record<string, string>
}
export type UploadTheme = 'default' | 'element-plus' | 'ant-design-vue' | ThemeAdapter
